name: I've had enough of it, enough of it

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "GOAMD64=v4"
            nickname: "linux-glibc-amd64v4"
          - tag: "GOAMD64=v3"
            nickname: "linux-glibc-amd64v3"
          - tag: "GOAMD64=v2"
            nickname: "linux-glibc-amd64v2"
          - tag: "GOAMD64=v1"
            nickname: "linux-glibc-amd64v1"
          - tag: ""
            nickname: "linux-glibc-amd64"
          - tag: "GOOS=darwin GOARCH=arm64"
            nickname: "darwin-arm64"
          - tag: "GOOS=windows GOARCH=amd64"
            nickname: "windows-amd64.exe"
          - tag: "CGO_ENABLED=0"
            nickname: "linux-musl-amd64"
            openwrt: "yes"
            patch_arch: "x86_64"
            sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - tag: "GOARCH=arm64"
            nickname: "linux-musl-arm64"
            openwrt: "yes"
            patch_arch: "aarch64_generic"
            sdk_name: "openwrt-sdk-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get Version & fuck cache
        id: get_version
        shell: bash
        run: |
          VERSION=$(grep 'const Version' cmd/version.go | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          mv go.mod go.mod.backup

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'

      - name: Build binary
        shell: bash
        run: |
          mv go.mod.backup go.mod
          ${{ matrix.tag }} go build
          mv go-rustdesk-server* go-rustdesk-server-${{ matrix.nickname }}

      - name: Preparing build environment
        if: matrix.openwrt == 'yes'
        uses: mokanove/mokanove/actions/build-env@main

      - name: Prepare SDK
        if: matrix.openwrt == 'yes'
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}

      - name: Preparation before compilation
        if: matrix.openwrt == 'yes'
        env:
          PKG_VERSION: ${{ steps.get_version.outputs.version }}
          PKG_ARCH: ${{ matrix.patch_arch }}
        shell: bash
        run: |
          mkdir -p ${{ matrix.sdk_name }}/package/rsop/root/etc/init.d
          mkdir -p ${{ matrix.sdk_name }}/package/rsop/root/etc/rustdesk

          printf '%s\n' \
            'include $(TOPDIR)/rules.mk' \
            "PKG_NAME:=rsop" \
            "PKG_VERSION:=${PKG_VERSION}" \
            "PKG_RELEASE:=1" \
            "PKG_LICENSE:=MoPL" \
            "LUCI_TITLE:=Rustdesk Server(Golang implementation) for OpenWrt" \
            "LUCI_PKGARCH:=${PKG_ARCH}" \
            'include $(TOPDIR)/feeds/luci/luci.mk' \
            '# call BuildPackage - OpenWrt buildroot signature' \
            > ${{ matrix.sdk_name }}/package/rsop/Makefile

          printf '%s\n' \
            '#!/bin/sh /etc/rc.common' \
            'START=99' \
            'STOP=10' \
            'USE_PROCD=1' \
            'DATA_DIR="/etc/rustdesk"' \
            'GORS_BIN="/etc/rustdesk/go-rustdesk-server"' \
            'start_service() {' \
            '    procd_open_instance "go-rustdesk-server"' \
            '    procd_set_param command sh -c "cd '"'"'$DATA_DIR'"'"' && exec '"'"'$GORS_BIN'"'"'"' \
            '    procd_set_param respawn 3600 3 3' \
            '    procd_set_param stdout 1' \
            '    procd_set_param stderr 1' \
            '    procd_set_param env RUST_LOG=debug' \
            '    procd_close_instance' \
            '}' \
            'service_triggers() {' \
            '    procd_add_reload_trigger "rsop"' \
            '}' \
            > ${{ matrix.sdk_name }}/package/rsop/root/etc/init.d/rsop

          cp $GITHUB_WORKSPACE/go-rustdesk-server-${{ matrix.nickname }} ${{ matrix.sdk_name }}/package/rsop/root/etc/rustdesk/go-rustdesk-server
          chmod +x ${{ matrix.sdk_name }}/package/rsop/root/etc/rustdesk/go-rustdesk-server
          chmod +x ${{ matrix.sdk_name }}/package/rsop/root/etc/init.d/rsop

      - name: Build for OpenWrt
        if: matrix.openwrt == 'yes'
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}
          make package/rsop/compile V=s -j$(nproc)

      - name: Rename compilation files
        if: matrix.openwrt == 'yes'
        shell: bash
        run: |
          mv ${{ matrix.sdk_name }}/bin/packages/*/base/*.apk rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
            go-rustdesk-server*
            rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk
          body: |
            # 📝 Release Notes
            - Add GOAMD64 binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
